import os
from pathlib import Path


def _env_flag(name, default=False):
    value = os.getenv(name)
    if value is None:
        return bool(default)
    return value.strip().lower() in {"1", "true", "yes", "on"}

BASE_DIR = Path(__file__).resolve().parent
ASSETS_DIR = str(BASE_DIR / "Assets")
LOGS_DIR = str(BASE_DIR / "logs")
MEMORY_DIR = BASE_DIR / "memory"

WINDOW_TITLE = "EatventureAuto"
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 780

DEBUG = False
ShowForbiddenArea = False

MATCH_THRESHOLD = 0.98
RED_ICON_THRESHOLD = 0.920
NEW_LEVEL_RED_ICON_THRESHOLD = 0.942
STATS_RED_ICON_THRESHOLD = 0.943
UPGRADE_STATION_THRESHOLD = 0.910
BOX_THRESHOLD = 0.904
BOX_COLOR_CHECK = False
BOX_COLOR_THRESHOLD = 0.5
BOX_HSV_COLOR_GATE_ENABLED = True
BOX_HSV_RANGES = (
    ((10, 65, 180), (13, 105, 255)),
    ((13, 90, 120), (15, 190, 245)),
    ((18, 90, 120), (18, 190, 245)),
    ((23, 30, 140), (32, 125, 255)),
)
BOX_HSV_MIN_MATCH_RATIO = 0.405
UNLOCK_THRESHOLD = 0.905
NEW_LEVEL_THRESHOLD = 0.965
RED_ICON_MIN_MATCHES = 6

CLICK_DELAY = 0.120
MOUSE_MOVE_DELAY = 0.030
HOVER_ENABLED = True
HOVER_DURATION = 0.075
UPGRADE_SEARCH_INTERVAL = 0.220
STATE_DELAY = 0.240
UPGRADE_STATION_VERIFY_SETTLE_DELAY = 0.900
UPGRADE_STATION_VERIFY_SEARCH_ATTEMPTS = 5
UPGRADE_STATION_VERIFY_SEARCH_INTERVAL = 0.300

TELEGRAM_ENABLED = _env_flag("EATVENTURE_TELEGRAM_ENABLED", False)
TELEGRAM_BOT_TOKEN = os.getenv("EATVENTURE_TELEGRAM_BOT_TOKEN", os.getenv("TELEGRAM_BOT_TOKEN", "")).strip()
TELEGRAM_CHAT_ID = os.getenv("EATVENTURE_TELEGRAM_CHAT_ID", os.getenv("TELEGRAM_CHAT_ID", "")).strip()
TELEGRAM_QUEUE_MAXSIZE = 100
TELEGRAM_CLOSE_TIMEOUT = 6.0

MAX_SEARCH_Y = 660
EXTENDED_SEARCH_Y = 710
UPGRADE_STATION_SEARCH_Y = 710

IDLE_CLICK_POS = (2, 390)
STATS_UPGRADE_BUTTON_POS = (310, 698)
STATS_UPGRADE_POS = (270, 304)
SCROLL_START_POS = (170, 380)
NEW_LEVEL_BUTTON_POS = (30, 692)
LEVEL_TRANSITION_POS = (174, 520)

UPGRADE_STATION_COLOR_CHECK = False
UPGRADE_STATION_HSV_COLOR_GATE_ENABLED = True
UPGRADE_STATION_HSV_RANGES = (
    ((12, 88, 185), (29, 199, 252)),
    ((100, 135, 204), (103, 191, 255)),
)
UPGRADE_STATION_HSV_MIN_MATCH_RATIO = 0.50

STATS_UPGRADE_CLICK_DURATION = 2
STATS_UPGRADE_CLICK_DELAY = 0.016

RED_ICON_OFFSET_X = 10
RED_ICON_OFFSET_Y = 10

NEW_LEVEL_RED_ICON_X_MIN = 40
NEW_LEVEL_RED_ICON_X_MAX = 60
NEW_LEVEL_RED_ICON_Y_MIN = 665
NEW_LEVEL_RED_ICON_Y_MAX = 680

UPGRADE_RED_ICON_X_MIN = 280
UPGRADE_RED_ICON_X_MAX = 310
UPGRADE_RED_ICON_Y_MIN = 665
UPGRADE_RED_ICON_Y_MAX = 680

SCROLL_PIXEL_STEP = 125
SCROLL_DISTANCE_RATIO = 1.0
MAX_SCROLL_CYCLES = 3
SCROLL_INCREMENT_STEP = 2
SCROLL_INTERVAL_PAUSE = 0.250
POST_SCROLL_SETTLE = 0.250
SCROLL_DURATION = 0.250

SPAM_CLICK_DURATION = 2.8
SPAM_CLICK_DELAY = 0.052
SPAM_CLICK_JITTER = 0
RAPID_CLICK_DOWN_UP_DELAY = 0.012

ADAPTIVE_TUNER_ENABLED = False
ADAPTIVE_TUNER_ALPHA = 0.18
ADAPTIVE_TUNER_CLICK_LOW_THRESHOLD = 0.96
ADAPTIVE_TUNER_CLICK_HIGH_THRESHOLD = 0.995
ADAPTIVE_TUNER_SEARCH_LOW_THRESHOLD = 0.90
ADAPTIVE_TUNER_SEARCH_HIGH_THRESHOLD = 0.985
ADAPTIVE_TUNER_CLICK_DELAY_STEP = 0.018
ADAPTIVE_TUNER_MOVE_DELAY_STEP = 0.004
ADAPTIVE_TUNER_CLICK_DECREMENT = 0.003
ADAPTIVE_TUNER_MOVE_DECREMENT = 0.0015
ADAPTIVE_TUNER_SEARCH_INTERVAL_STEP = 0.025
ADAPTIVE_TUNER_SEARCH_DECREMENT = 0.006
ADAPTIVE_TUNER_MIN_CLICK_DELAY = 0.105
ADAPTIVE_TUNER_MAX_CLICK_DELAY = 0.240
ADAPTIVE_TUNER_MIN_MOVE_DELAY = 0.024
ADAPTIVE_TUNER_MAX_MOVE_DELAY = 0.050
ADAPTIVE_TUNER_MIN_SEARCH_INTERVAL = 0.190
ADAPTIVE_TUNER_MAX_SEARCH_INTERVAL = 0.360

AI_VISION_ENABLED = False
AI_VISION_ALPHA = 0.18
AI_VISION_ALPHA_MAX = 0.35
AI_VISION_CONFIDENCE_BOOST = 0.10
AI_VISION_CONFIDENCE_THRESHOLD = 0.96

AI_BOX_THRESHOLD_MIN = 0.904
AI_BOX_THRESHOLD_MAX = 0.904
AI_BOX_MISS_WINDOW = 3
AI_BOX_MISS_STEP = 0.0020

AI_RED_ICON_THRESHOLD_MIN = 0.942
AI_RED_ICON_THRESHOLD_MAX = 0.942
AI_RED_ICON_MARGIN = 0.012
AI_RED_ICON_MISS_WINDOW = 5
AI_RED_ICON_MISS_STEP = 0.0010

AI_NEW_LEVEL_THRESHOLD_MIN = 0.945
AI_NEW_LEVEL_THRESHOLD_MAX = 0.988
AI_NEW_LEVEL_MISS_WINDOW = 3
AI_NEW_LEVEL_MISS_STEP = 0.0025

AI_NEW_LEVEL_RED_ICON_THRESHOLD_MIN = 0.942
AI_NEW_LEVEL_RED_ICON_THRESHOLD_MAX = 0.942
AI_NEW_LEVEL_RED_ICON_MISS_WINDOW = 5
AI_NEW_LEVEL_RED_ICON_MISS_STEP = 0.0010

AI_UPGRADE_STATION_THRESHOLD_MIN = 0.918
AI_UPGRADE_STATION_THRESHOLD_MAX = 0.918
AI_UPGRADE_STATION_MISS_WINDOW = 3
AI_UPGRADE_STATION_MISS_STEP = 0.0020

AI_STATS_UPGRADE_THRESHOLD_MIN = 0.942
AI_STATS_UPGRADE_THRESHOLD_MAX = 0.942
AI_STATS_UPGRADE_MISS_WINDOW = 3
AI_STATS_UPGRADE_MISS_STEP = 0.0010

AI_VISION_STATE_FILE = str(MEMORY_DIR / "vision_state.json")
AI_VISION_SAVE_INTERVAL = 12.0

AI_LEARNING_ENABLED = False
AI_LEARNING_STATE_FILE = str(MEMORY_DIR / "learning_state_stable.json")
AI_LEARNING_SAVE_INTERVAL = 10.0
AI_LEARNING_RECORDS_LIMIT = 256
AI_LEARNING_THREAD_JOIN_TIMEOUT = 0.8
AI_LEARNING_THREAD_INTERVAL = 1.0
AI_LEARNING_PAIR_WINDOW = 5
AI_LEARNING_BATCH_WINDOW = 12
AI_LEARNING_EMA_ALPHA = 0.14
AI_LEARNING_PROFILE_BLEND_TOP_K = 3
AI_LEARNING_MIN_IMPROVEMENT_RATIO = 0.05
AI_LEARNING_APPLY_COOLDOWN = 30.0
AI_LEARNING_MIN_CLICK_DELAY = 0.105
AI_LEARNING_MAX_CLICK_DELAY = 0.240
AI_LEARNING_MIN_MOVE_DELAY = 0.024
AI_LEARNING_MAX_MOVE_DELAY = 0.050
AI_LEARNING_MIN_SEARCH_INTERVAL = 0.190
AI_LEARNING_MAX_SEARCH_INTERVAL = 0.360
LEARNING_LOOP_MIN_SLEEP = 0.75

FORBIDDEN_CLICK_X_MIN = 60
FORBIDDEN_CLICK_X_MAX = 260
FORBIDDEN_CLICK_Y_MIN = 668

FORBIDDEN_ZONE_1_X_MIN = 290
FORBIDDEN_ZONE_1_X_MAX = 350
FORBIDDEN_ZONE_1_Y_MIN = 93
FORBIDDEN_ZONE_1_Y_MAX = 320

FORBIDDEN_ZONE_2_X_MIN = 0
FORBIDDEN_ZONE_2_X_MAX = 60
FORBIDDEN_ZONE_2_Y_MIN = 50
FORBIDDEN_ZONE_2_Y_MAX = 280

FORBIDDEN_ZONE_3_X_MIN = 0
FORBIDDEN_ZONE_3_X_MAX = 60
FORBIDDEN_ZONE_3_Y_MIN = 600
FORBIDDEN_ZONE_3_Y_MAX = 667

FORBIDDEN_ZONE_4_X_MIN = 145
FORBIDDEN_ZONE_4_X_MAX = 200
FORBIDDEN_ZONE_4_Y_MIN = 65
FORBIDDEN_ZONE_4_Y_MAX = 110

FORBIDDEN_ZONE_5_X_MIN = 55
FORBIDDEN_ZONE_5_X_MAX = 260
FORBIDDEN_ZONE_5_Y_MIN = 660
FORBIDDEN_ZONE_5_Y_MAX = 725
