from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

WINDOW_TITLE = "EatventureAuto"
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 780

DEBUG = False
DEBUG_VISION = False
ShowForbiddenArea = False

ASSETS_DIR = str(BASE_DIR / "Assets")
TEMPLATES_DIR = ASSETS_DIR
LOGS_DIR = str(BASE_DIR / "logs")

MATCH_THRESHOLD = 0.975
RED_ICON_THRESHOLD = 0.92
NEW_LEVEL_RED_ICON_THRESHOLD = 0.942
STATS_RED_ICON_THRESHOLD = 0.973
UPGRADE_STATION_THRESHOLD = 0.95
BOX_THRESHOLD = 0.973
UNLOCK_THRESHOLD = 0.958
NEW_LEVEL_THRESHOLD = 0.984

RED_ICON_MIN_MATCHES = 1
NEW_LEVEL_RED_ICON_MIN_MATCHES = 1
RED_ICON_PIXEL_THRESHOLD = 50
RED_ICON_DILATE_KERNEL = 3

RED_HSV_LOWER1 = (0, 120, 130)
RED_HSV_UPPER1 = (10, 255, 255)
RED_HSV_LOWER2 = (165, 120, 130)
RED_HSV_UPPER2 = (179, 255, 255)

RED_ICON_COLOR_CHECK = True
RED_ICON_COLOR_MIN_RATIO = 1.35
RED_ICON_COLOR_MAX_RATIO = 3.50
RED_ICON_COLOR_MIN_MEAN = 56
RED_ICON_COLOR_SAMPLE_SIZE = 24

RED_ICON_TEMPLATE_VERIFY = True
RED_ICON_TEMPLATE_VERIFY_MAX_OFFSET = 1
RED_ICON_TEMPLATE_MIN_COVERAGE = 0.30
RED_ICON_TEMPLATE_MIN_PRECISION = 0.56
RED_ICON_TEMPLATE_MIN_RECALL = 0.56
RED_ICON_TEMPLATE_MIN_IOU = 0.40
RED_ICON_TEMPLATE_COLOR_SIMILARITY = 0.43

RED_ICON_VERIFY_PADDING = 24
RED_ICON_VERIFY_TOLERANCE = 12
RED_ICON_REFINE_RADIUS = 18
RED_ICON_REFINE_THRESHOLD_DROP = 0.02

UPGRADE_STATION_COLOR_CHECK = True
UPGRADE_STATION_REFINE_RADIUS = 28
UPGRADE_STATION_CLICK_REFINE_RADIUS = 18

UPGRADE_STATION_HSV_LOWER = (90, 100, 195)
UPGRADE_STATION_HSV_UPPER = (106, 210, 255)
UPGRADE_STATION_HSV_MIN_RATIO = 0.55

COLOR_SIMILARITY_THRESHOLD = 0.70
VERIFY_THRESHOLD = 0.97
VERIFY_PADDING = 32

CLICK_DELAY = 0.016
MOUSE_MOVE_DELAY = 0.008
MOUSE_DOWN_UP_DELAY = 0.008
DOUBLE_CLICK_DELAY = 0.024

MOUSE_MOVE_RETRIES = 2
MOUSE_MOVE_RETRY_DELAY = 0.008
MOUSE_TARGET_SETTLE_DELAY = 0.008
MOUSE_TARGET_TIMEOUT = 0.032
MOUSE_TARGET_CHECK_INTERVAL = 0.004
MOUSE_TARGET_HOVER_DELAY = 0.004
MOUSE_STABILIZE_DURATION = 0.004
MOUSE_TARGET_RETRIES = 2
MOUSE_TARGET_CORRECTION_DELAY = 0.004
MOUSE_POSITION_TOLERANCE = 1

MOUSE_PRE_CLICK_STABILIZE_BASE = 0.004
MOUSE_PRE_CLICK_STABILIZE_MAX = 0.016
MOUSE_PRE_CLICK_STABILIZE_DISTANCE_FACTOR = 0.00002

MOUSE_CLICK_RETRY_COUNT = 2
MOUSE_CLICK_RETRY_SETTLE_DELAY = 0.004
MIN_CLICK_INTERVAL = 0.016

SCROLL_START_POS = (170, 380)
SCROLL_PIXEL_STEP = 90
SCROLL_DISTANCE_RATIO = 1
SCROLL_VERIFICATION_DISTANCE = 168
MAX_SCROLL_CYCLES = 12
SCROLL_INCREMENT_STEP = 1
SCROLL_INTERVAL_PAUSE = 0.016
POST_SCROLL_SETTLE = 0.032
CYCLE_PAUSE_DURATION = 0.016
SCROLL_DURATION = 0.144
SCROLL_STEP_COUNT = 8
SCROLL_MIN_INTERVAL = 0.016
OSCILLATION_CYCLE_COOLDOWN = 0.016
SCROLL_SETTLE_DELAY = 0.016

MAIN_LOOP_DELAY = 0.008
STATE_DELAY = 0.016
STATE_MIN_INTERVAL_DEFAULT = 0.016
STATE_MIN_INTERVALS = {
    "FIND_RED_ICONS": 0.048,
    "OPEN_BOXES": 0.032,
    "SCROLL": 0.048,
    "SEARCH_UPGRADE_STATION": 0.064,
    "CLICK_RED_ICON": 0.032,
    "HOLD_UPGRADE_STATION": 0.048,
    "CHECK_UNLOCK": 0.032,
    "CHECK_NEW_LEVEL": 0.032,
    "UPGRADE_STATS": 0.032,
    "TRANSITION_LEVEL": 0.064,
    "WAIT_FOR_UNLOCK": 0.032,
}

RED_ICON_OFFSET_X = 10
RED_ICON_OFFSET_Y = 10

NEW_LEVEL_POS = (171, 434)
LEVEL_TRANSITION_POS = (174, 520)
IDLE_CLICK_POS = (2, 390)
STATS_UPGRADE_POS = (270, 304)
STATS_UPGRADE_BUTTON_POS = (310, 698)
NEW_LEVEL_BUTTON_POS = (30, 692)

UPGRADE_HOLD_DURATION = 6
UPGRADE_CLICK_INTERVAL = 0.016

SPAM_CLICK_DURATION = 4
SPAM_CLICK_DELAY = 0.016
SPAM_CLICK_JITTER = 0
RAPID_CLICK_DOWN_UP_DELAY = 0.0016
RAPID_CLICK_SPIN_THRESHOLD = 0.016

UPGRADE_SEARCH_INTERVAL = 0.064

STATS_UPGRADE_CLICK_DURATION = 1.0
STATS_UPGRADE_CLICK_DELAY = 0.016
STATS_ICON_PADDING = 20

IDLE_CLICK_SETTLE_DELAY = 0.016
IDLE_CLICK_COOLDOWN = 0.032

RED_ICON_MIN_DISTANCE = 80
RED_ICON_MERGE_PROXIMITY = 10
RED_ICON_MERGE_BUCKET_SIZE = 10

UPGRADE_STATION_SEARCH_MAX_ATTEMPTS = 5
UPGRADE_STATION_RELAXED_THRESHOLD_DROP = 0.035
UPGRADE_STATION_RELAXED_ATTEMPT_TRIGGER = 2

CAPTURE_CACHE_TTL = 0.016
NEW_LEVEL_RED_ICON_CACHE_TTL = 0.016
RED_ICON_STABILITY_CACHE_TTL = 1.40
RED_ICON_STABILITY_RADIUS = 12
RED_ICON_STABILITY_MIN_HITS = 3
RED_ICON_STABILITY_MAX_HISTORY = 14
RED_ICON_MAX_PER_SCAN = 1
RED_ICON_PRIORITY_TEMPLATE_LIMIT = 8
WAIT_FOR_UNLOCK_MAX_ATTEMPTS = 50

FORBIDDEN_ZONE_DETECTION_PRE_DELAY = 0.008
FORBIDDEN_ZONE_DETECTION_POST_DELAY = 0.008
FORBIDDEN_ZONE_DEBOUNCE_TICKS = 3
FORBIDDEN_ZONE_DEBOUNCE_REQUIRED_CONSENSUS = 2
FORBIDDEN_ZONE_SCROLL_REENTRY_COOLDOWN = 0.16
FORBIDDEN_BLACKOUT_DURATION = 2.0

FORBIDDEN_ZONE_PRECLICK_VALIDATION_DELAY = 0.004
FORBIDDEN_ZONE_DOUBLE_CHECK_DELAY = 0.004
ASSET_BOUNDARY_PRECHECK_DELAY = 0.004
ASSET_BOUNDARY_CONFIRM_DELAY = 0.004
ASSET_SEGREGATION_DELAY = 0.004

LEVEL_TRANSITION_MAX_ATTEMPTS = 5
LEVEL_COMPLETION_RECENCY_WINDOW = 5.0
NEW_LEVEL_FAIL_COOLDOWN = 4.0

NEW_LEVEL_BUTTON_DELAY = 0.048
NEW_LEVEL_FOLLOWUP_DELAY = 0.800
TRANSITION_POST_CLICK_DELAY = 0.640
TRANSITION_RETRY_DELAY = 0.160

NEW_LEVEL_INTERRUPT_INTERVAL = 0.016
NEW_LEVEL_MONITOR_INTERVAL = 0.048
NEW_LEVEL_OVERRIDE_COOLDOWN = 0.160

NEW_LEVEL_RED_ICON_X_MIN = 40
NEW_LEVEL_RED_ICON_X_MAX = 60
NEW_LEVEL_RED_ICON_Y_MIN = 665
NEW_LEVEL_RED_ICON_Y_MAX = 680

UPGRADE_RED_ICON_X_MIN = 280
UPGRADE_RED_ICON_X_MAX = 310
UPGRADE_RED_ICON_Y_MIN = 665
UPGRADE_RED_ICON_Y_MAX = 680

MAX_SEARCH_Y = 660
EXTENDED_SEARCH_Y = 720

ENABLE_NEW_LEVEL_INTERRUPT = True
ENABLE_NO_ICON_SCROLL_INTERRUPT = True

ADAPTIVE_TUNER_ENABLED = True
ADAPTIVE_TUNER_ALPHA = 0.18

ADAPTIVE_TUNER_CLICK_LOW_THRESHOLD = 0.88
ADAPTIVE_TUNER_CLICK_HIGH_THRESHOLD = 0.99
ADAPTIVE_TUNER_SEARCH_LOW_THRESHOLD = 0.86
ADAPTIVE_TUNER_SEARCH_HIGH_THRESHOLD = 0.975

ADAPTIVE_TUNER_CLICK_DELAY_STEP = 0.004
ADAPTIVE_TUNER_MOVE_DELAY_STEP = 0.002
ADAPTIVE_TUNER_CLICK_DECREMENT = 0.002
ADAPTIVE_TUNER_MOVE_DECREMENT = 0.001
ADAPTIVE_TUNER_SEARCH_INTERVAL_STEP = 0.008
ADAPTIVE_TUNER_UPGRADE_INTERVAL_STEP = 0.0
ADAPTIVE_TUNER_SEARCH_DECREMENT = 0.004
ADAPTIVE_TUNER_UPGRADE_DECREMENT = 0.0

ADAPTIVE_TUNER_MIN_CLICK_DELAY = 0.008
ADAPTIVE_TUNER_MAX_CLICK_DELAY = 0.032
ADAPTIVE_TUNER_MIN_MOVE_DELAY = 0.004
ADAPTIVE_TUNER_MAX_MOVE_DELAY = 0.016
ADAPTIVE_TUNER_MIN_UPGRADE_INTERVAL = 0.008
ADAPTIVE_TUNER_MAX_UPGRADE_INTERVAL = 0.032
ADAPTIVE_TUNER_MIN_SEARCH_INTERVAL = 0.048
ADAPTIVE_TUNER_MAX_SEARCH_INTERVAL = 0.128

AI_VISION_ENABLED = True
AI_VISION_ALPHA = 0.12
AI_VISION_ALPHA_MAX = 0.24
AI_VISION_CONFIDENCE_BOOST = 0.10
AI_VISION_CONFIDENCE_THRESHOLD = 0.94

AI_BOX_THRESHOLD_MIN = 0.90
AI_BOX_THRESHOLD_MAX = 0.992
AI_BOX_MISS_WINDOW = 4
AI_BOX_MISS_STEP = 0.0025

AI_RED_ICON_THRESHOLD_MIN = 0.912
AI_RED_ICON_THRESHOLD_MAX = 0.948
AI_RED_ICON_BOOTSTRAP_MAX = 0.938
AI_RED_ICON_MARGIN = 0.015
AI_RED_ICON_MISS_WINDOW = 4
AI_RED_ICON_MISS_STEP = 0.0015

AI_NEW_LEVEL_THRESHOLD_MIN = 0.975
AI_NEW_LEVEL_THRESHOLD_MAX = 0.992
AI_NEW_LEVEL_MISS_WINDOW = 4
AI_NEW_LEVEL_MISS_STEP = 0.0020

AI_NEW_LEVEL_RED_ICON_THRESHOLD_MIN = 0.934
AI_NEW_LEVEL_RED_ICON_THRESHOLD_MAX = 0.987
AI_NEW_LEVEL_RED_ICON_MISS_WINDOW = 4
AI_NEW_LEVEL_RED_ICON_MISS_STEP = 0.0015

AI_UPGRADE_STATION_THRESHOLD_MIN = 0.93
AI_UPGRADE_STATION_THRESHOLD_MAX = 0.988
AI_UPGRADE_STATION_MISS_WINDOW = 4
AI_UPGRADE_STATION_MISS_STEP = 0.0020

AI_STATS_UPGRADE_THRESHOLD_MIN = 0.93
AI_STATS_UPGRADE_THRESHOLD_MAX = 0.988
AI_STATS_UPGRADE_MISS_WINDOW = 4
AI_STATS_UPGRADE_MISS_STEP = 0.0020

AI_VISION_STATE_FILE = str(BASE_DIR / "memory" / "vision_state.json")
AI_VISION_SAVE_INTERVAL = 8.0

AI_LEARNING_ENABLED = True
AI_LEARNING_STATE_FILE = str(BASE_DIR / "memory" / "learning_state.json")
AI_LEARNING_SAVE_INTERVAL = 1.25
AI_LEARNING_RECORDS_LIMIT = 256
AI_LEARNING_THREAD_JOIN_TIMEOUT = 1.0
AI_LEARNING_THREAD_INTERVAL = 0.35
AI_LEARNING_PAIR_WINDOW = 3
AI_LEARNING_BATCH_WINDOW = 10
AI_LEARNING_EMA_ALPHA = 0.22
AI_LEARNING_PROFILE_BLEND_TOP_K = 4
AI_LEARNING_MIN_IMPROVEMENT_RATIO = 0.025
AI_LEARNING_APPLY_COOLDOWN = 1.2

AI_LEARNING_MIN_CLICK_DELAY = 0.008
AI_LEARNING_MAX_CLICK_DELAY = 0.032
AI_LEARNING_MIN_MOVE_DELAY = 0.004
AI_LEARNING_MAX_MOVE_DELAY = 0.016
AI_LEARNING_MIN_UPGRADE_INTERVAL = 0.008
AI_LEARNING_MAX_UPGRADE_INTERVAL = 0.032
AI_LEARNING_MIN_SEARCH_INTERVAL = 0.048
AI_LEARNING_MAX_SEARCH_INTERVAL = 0.128

OVERLAY_UPDATE_INTERVAL = 0.064
LEARNING_LOOP_MIN_SLEEP = 0.016
MONITOR_YIELD_BACKOFF = 0.128
MONITOR_POLL_MIN_SLEEP = 0.016
BACKUP_CLICK_GAP = 0.064
UNLOCK_REGISTER_WAIT = 0.064
VERIFICATION_SCROLL_DURATION = 0.128
UNLOCK_HOT_LOOP_TIMEOUT = 5.0
UNLOCK_POLL_INTERVAL = 0.016
THREAD_JOIN_TIMEOUT = 1.0
HOLD_ITERATION_INTERVAL = 0.032
DRAG_MIN_DURATION = 0.008
DEFAULT_DRAG_DURATION = 0.160

TELEGRAM_ENABLED = True

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""

FORBIDDEN_ZONES = [
    {
        "name": "General bottom bar",
        "coordinate_space": "image",
        "x_min": 60,
        "x_max": 280,
        "y_min": 668,
        "y_max": 1000,
    },
    {
        "name": "Zone 1: Right side menu area",
        "coordinate_space": "image",
        "x_min": 290,
        "x_max": 350,
        "y_min": 93,
        "y_max": 320,
    },
    {
        "name": "Zone 2: Left side top menu area",
        "coordinate_space": "image",
        "x_min": 0,
        "x_max": 60,
        "y_min": 50,
        "y_max": 280,
    },
    {
        "name": "Zone 3: Left side bottom menu area",
        "coordinate_space": "image",
        "x_min": 0,
        "x_max": 60,
        "y_min": 590,
        "y_max": 667,
    },
    {
        "name": "Zone 4: Top center notification area",
        "coordinate_space": "image",
        "x_min": 145,
        "x_max": 200,
        "y_min": 65,
        "y_max": 110,
    },
    {
        "name": "Zone 5: Bottom navigation bar",
        "coordinate_space": "image",
        "x_min": 55,
        "x_max": 285,
        "y_min": 660,
        "y_max": 725,
    },
    {
        "name": "Zone 6: Top bar area",
        "coordinate_space": "image",
        "x_min": 0,
        "x_max": 360,
        "y_min": 0,
        "y_max": 70,
    },
]
